/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "action.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(iotextypes_Transfer, iotextypes_Transfer, AUTO)


PB_BIND(iotextypes_Candidate, iotextypes_Candidate, AUTO)


PB_BIND(iotextypes_CandidateList, iotextypes_CandidateList, AUTO)


PB_BIND(iotextypes_PutPollResult, iotextypes_PutPollResult, AUTO)


PB_BIND(iotextypes_Execution, iotextypes_Execution, AUTO)


PB_BIND(iotextypes_StakeCreate, iotextypes_StakeCreate, AUTO)


PB_BIND(iotextypes_StakeReclaim, iotextypes_StakeReclaim, AUTO)


PB_BIND(iotextypes_StakeAddDeposit, iotextypes_StakeAddDeposit, AUTO)


PB_BIND(iotextypes_StakeRestake, iotextypes_StakeRestake, AUTO)


PB_BIND(iotextypes_StakeChangeCandidate, iotextypes_StakeChangeCandidate, AUTO)


PB_BIND(iotextypes_StakeTransferOwnership, iotextypes_StakeTransferOwnership, AUTO)


PB_BIND(iotextypes_CandidateBasicInfo, iotextypes_CandidateBasicInfo, AUTO)


PB_BIND(iotextypes_CandidateRegister, iotextypes_CandidateRegister, AUTO)


PB_BIND(iotextypes_StartSubChain, iotextypes_StartSubChain, AUTO)


PB_BIND(iotextypes_StopSubChain, iotextypes_StopSubChain, AUTO)


PB_BIND(iotextypes_MerkleRoot, iotextypes_MerkleRoot, AUTO)


PB_BIND(iotextypes_PutBlock, iotextypes_PutBlock, AUTO)


PB_BIND(iotextypes_CreateDeposit, iotextypes_CreateDeposit, AUTO)


PB_BIND(iotextypes_SettleDeposit, iotextypes_SettleDeposit, AUTO)


PB_BIND(iotextypes_CreatePlumChain, iotextypes_CreatePlumChain, AUTO)


PB_BIND(iotextypes_TerminatePlumChain, iotextypes_TerminatePlumChain, AUTO)


PB_BIND(iotextypes_PlumPutBlock, iotextypes_PlumPutBlock, AUTO)


PB_BIND(iotextypes_PlumPutBlock_RootsEntry, iotextypes_PlumPutBlock_RootsEntry, AUTO)


PB_BIND(iotextypes_PlumCreateDeposit, iotextypes_PlumCreateDeposit, AUTO)


PB_BIND(iotextypes_PlumStartExit, iotextypes_PlumStartExit, AUTO)


PB_BIND(iotextypes_PlumChallengeExit, iotextypes_PlumChallengeExit, AUTO)


PB_BIND(iotextypes_PlumResponseChallengeExit, iotextypes_PlumResponseChallengeExit, AUTO)


PB_BIND(iotextypes_PlumFinalizeExit, iotextypes_PlumFinalizeExit, AUTO)


PB_BIND(iotextypes_PlumSettleDeposit, iotextypes_PlumSettleDeposit, AUTO)


PB_BIND(iotextypes_PlumTransfer, iotextypes_PlumTransfer, AUTO)


PB_BIND(iotextypes_ActionCore, iotextypes_ActionCore, AUTO)


PB_BIND(iotextypes_Action, iotextypes_Action, AUTO)


PB_BIND(iotextypes_Receipt, iotextypes_Receipt, AUTO)


PB_BIND(iotextypes_Log, iotextypes_Log, AUTO)


PB_BIND(iotextypes_Logs, iotextypes_Logs, AUTO)


PB_BIND(iotextypes_EvmTransfer, iotextypes_EvmTransfer, AUTO)


PB_BIND(iotextypes_EvmTransferList, iotextypes_EvmTransferList, AUTO)


PB_BIND(iotextypes_ActionEvmTransfer, iotextypes_ActionEvmTransfer, AUTO)


PB_BIND(iotextypes_BlockEvmTransfer, iotextypes_BlockEvmTransfer, AUTO)


PB_BIND(iotextypes_DepositToRewardingFund, iotextypes_DepositToRewardingFund, AUTO)


PB_BIND(iotextypes_ClaimFromRewardingFund, iotextypes_ClaimFromRewardingFund, AUTO)


PB_BIND(iotextypes_GrantReward, iotextypes_GrantReward, AUTO)




